### ISSUE TITLE
Server error `500` on install, Log message: `RequirementsNotFound: Requirements for toggl_track not found: ['lib-toggl==0.1.2']`

### ISSUE THREAD

**Issue by kquinsland** [kquinsland/ha-toggl-track#1]
This manifests after the `config/custom_components/toggl_track` folder is created and filled with the correct content and then trying to actually set up the integration.

Error shown to the user:

```text
 Config flow could not be loaded: 500 Internal Server Error Server got itself in trouble 
```

And in logs:

```text
2023-12-27 16:50:19.308 INFO (SyncWorker_4) [homeassistant.util.package] Attempting install of lib-toggl==0.1.2
2023-12-27 16:50:19.308 DEBUG (SyncWorker_4) [homeassistant.util.package] Running pip command: args=['/usr/local/bin/python3', '-m', 'pip', 'install', '--quiet', 'lib-toggl==0.1.2', '--timeout', '60', '--upgrade', '--constraint', '/workspaces/ha-core/homeassistant/package_constraints.txt']
2023-12-27 16:50:19.953 ERROR (SyncWorker_4) [homeassistant.util.package] Unable to install package lib-toggl==0.1.2: ERROR: Cannot install lib-toggl==0.1.2 because these package versions have conflicting dependencies.
ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts

[notice] A new release of pip is available: 23.1.2 -> 23.3.2
[notice] To update, run: pip install --upgrade pip
2023-12-27 16:50:19.953 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_protocol.py", line 452, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_app.py", line 543, in _handle
    resp = await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_middlewares.py", line 114, in impl
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/workspaces/ha-core/homeassistant/components/http/security_filter.py", line 85, in security_filter_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/workspaces/ha-core/homeassistant/components/http/forwarded.py", line 100, in forwarded_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/workspaces/ha-core/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/workspaces/ha-core/homeassistant/components/http/ban.py", line 80, in ban_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/workspaces/ha-core/homeassistant/components/http/auth.py", line 233, in auth_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/workspaces/ha-core/homeassistant/components/http/headers.py", line 31, in headers_middleware
    response = await handler(request)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/workspaces/ha-core/homeassistant/components/http/view.py", line 149, in handle
    result = await handler(request, **request.match_info)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspaces/ha-core/homeassistant/components/http/decorators.py", line 63, in with_admin
    return await func(self, request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspaces/ha-core/homeassistant/components/config/config_entries.py", line 147, in post
    return await super().post(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspaces/ha-core/homeassistant/components/http/data_validator.py", line 72, in wrapper
    result = await method(view, request, data, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspaces/ha-core/homeassistant/helpers/data_entry_flow.py", line 71, in post
    result = await self._flow_mgr.async_init(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspaces/ha-core/homeassistant/config_entries.py", line 888, in async_init
    flow, result = await task
                   ^^^^^^^^^^
  File "/workspaces/ha-core/homeassistant/config_entries.py", line 906, in _async_init
    flow = await self.async_create_flow(handler, context=context, data=data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspaces/ha-core/homeassistant/config_entries.py", line 1009, in async_create_flow
    handler = await _async_get_flow_handler(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspaces/ha-core/homeassistant/config_entries.py", line 2106, in _async_get_flow_handler
    await _load_integration(hass, domain, hass_config)
  File "/workspaces/ha-core/homeassistant/config_entries.py", line 2082, in _load_integration
    await async_process_deps_reqs(hass, hass_config, integration)
  File "/workspaces/ha-core/homeassistant/setup.py", line 466, in async_process_deps_reqs
    await requirements.async_get_integration_with_requirements(
  File "/workspaces/ha-core/homeassistant/requirements.py", line 52, in async_get_integration_with_requirements
    return await manager.async_get_integration_with_requirements(domain)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspaces/ha-core/homeassistant/requirements.py", line 168, in async_get_integration_with_requirements
    await self._async_process_integration(integration, done)
  File "/workspaces/ha-core/homeassistant/requirements.py", line 183, in _async_process_integration
    await self.async_process_requirements(
  File "/workspaces/ha-core/homeassistant/requirements.py", line 248, in async_process_requirements
    await self._async_process_requirements(name, missing)
  File "/workspaces/ha-core/homeassistant/requirements.py", line 286, in _async_process_requirements
    raise RequirementsNotFound(name, list(failures))
homeassistant.requirements.RequirementsNotFound: Requirements for toggl_track not found: ['lib-toggl==0.1.2'].
```

This is caused by this issue: https://github.com/kquinsland/lib-toggl/issues/3.

In short, `lib-toggl` wants to use a version of Pydantic that Home Assistant doesn't want to / can't support.

**Technically** you can still "force" the install of `lib-toggl` by getting a shell into Home Assistant and running `pip install lib-toggl==0.1.2`. This will install the correct version of pydantic and that'll allow lib-toggl install but it _can_ break other parts of your Home Assistant install so do so with _extreme caution_.

**Comment by kquinsland** [comment]
Fixed via: https://github.com/kquinsland/lib-toggl/pull/5

**Comment by charlie969** [comment]
@kquinsland I'm confused about whether this issue has been fixed - the README still notes "As of now lib-toggl can't be safely installed into Home Assistant via HACS." Does this need updating?

**Comment by kquinsland** [comment]
> [@kquinsland](https://github.com/kquinsland) I'm confused about whether this issue has been fixed - the README still notes "As of now lib-toggl can't be safely installed into Home Assistant via HACS." Does this need updating?

HACS install was possible once this issue was [resolved](https://github.com/kquinsland/ha-toggl-track/issues/1#issuecomment-1879766638). I removed that from the readme.
